version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: workshop-dvwa
    hostname: workshop-dvwa
    ports:
      - '1337:80'
  cve-2016-10033:
    image: vulnerables/cve-2016-10033
    container_name: workshop-cve-2016-10033
    hostname: workshop-cve-2016-10033
    ports:
      - '1338:80'
  phpldapadmin-remote-dump:
    image: vulnerables/phpldapadmin-remote-dump
    container_name: workshop-phpldapadmin-remote-dump
    hostname: workshop-phpldapadmin-remote-dump
    ports:
      - '1339:80'
  web-cpanel:
    build:
      context: web-cpanel
      dockerfile: Dockerfile
    container_name: workshop-web-cpanel
    hostname: workshop-web-cpanel
    ports:
      - '1340:80'
  web-jwt:
    build:
      context: jwt
      dockerfile: Dockerfile
    container_name: workshop-jwt
    hostname: workshop-jwt
    ports:
      - '1341:80'
  web-lfi:
    build:
      context: lfi
      dockerfile: Dockerfile
    container_name: workshop-lfi
    hostname: workshop-lfi
    ports:
      - '1342:80'
  web-sqli:
    build:
      context: sqli
      dockerfile: Dockerfile
    container_name: workshop-sqli
    hostname: workshop-sqli
    ports:
      - '1343:80'
  web-xss:
    build:
      context: xss
      dockerfile: Dockerfile
    container_name: workshop-xss
    hostname: workshop-xss
    ports:
      - '1344:80'